export enum Lessons {
  'JAVASCRIPT_ESSENTIALS' = 'JavaScript Essentials',
  'REACT_FUNDAMENTALS' = 'React Fundamentals',
  'REACT_ROUTER' = 'React Router',
  'REDUX' = 'Redux',
  'NODE_JS' = 'Node.js',
  'EXPRESS' = 'Express',
  'MONGODB' = 'MongoDB',
  'MONGOOSE' = 'Mongoose',
  'GRAPHQL' = 'GraphQL',
  'APOLLO_CLIENT' = 'Apollo Client',
  'NEXT_JS' = 'Next.js',
  'TYPESCRIPT' = 'TypeScript',
  'JEST' = 'Jest',
  'CYPRESS' = 'Cypress',
  'STORYBOOK' = 'Storybook',
  'DOCKER' = 'Docker',
  'KUBERNETES' = 'Kubernetes',
  'AWS' = 'AWS',
  'GCP' = 'GCP',
  'AZURE' = 'Azure',
  'GIT' = 'Git',
  'GITHUB' = 'GitHub',
  'GITLAB' = 'GitLab',
  'BITBUCKET' = 'Bitbucket',
  'CI_CD' = 'CI/CD',
  'AGILE' = 'Agile',
  'SCRUM' = 'Scrum',
  'KANBAN' = 'Kanban',
  'DEVOPS' = 'DevOps',
  'SECURITY_FUNDAMENTALS' = 'Security Fundamentals',
  'OWASP' = 'OWASP',
  'SECURITY_AUDIT' = 'Security Audit',
  'SQL' = 'SQL',
}

export enum Status {
  'REQUESTED' = 'Requested',
  'COMPLETED' = 'Completed',
  'DONE' = 'Done',
  'CANCELLED' = 'Canceled',
  'BOOKED' = 'Booked',
}